FROM python:3.12-slim
WORKDIR /app

ENV PATH="${PATH}:/root/.local/bin"

COPY ui-requirements.txt .
RUN pip install --no-cache-dir -r ui-requirements.txt

COPY streamlit_app .
EXPOSE 8501

SHELL ["/bin/bash", "-c"]
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]